# Generated by Django 3.1.7 on 2021-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='insta_link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
